use_frameworks!

platform :ios, '8.0'

target 'testone_Example' do
  pod 'testone', :path => '../'

  target 'testone_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    ## pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
